// ps2_cntrlr.v

// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module ps2_cntrlr (
		input  wire       clk_clk,             //                           clk.clk
		input  wire [7:0] ps2_0_command,       // ps2_0_avalon_ps2_command_sink.data
		input  wire       ps2_0_command_valid, //                              .valid
		output wire       ps2_0_command_ready, //                              .ready
		input  wire       ps2_0_data_ready,    //  ps2_0_avalon_ps2_data_source.ready
		output wire [7:0] ps2_0_data,          //                              .data
		output wire       ps2_0_data_valid,    //                              .valid
		inout  wire       ps2_0_PS2_CLK,       //      ps2_0_external_interface.CLK
		inout  wire       ps2_0_PS2_DAT,       //                              .DAT
		input  wire       ps2_0_reset,         //                   ps2_0_reset.reset
		input  wire       reset_reset_n        //                         reset.reset_n
	);

	ps2_cntrlr_ps2_0 ps2_0 (
		.clk           (clk_clk),             //                     clk.clk
		.reset         (ps2_0_reset),         //                   reset.reset
		.command       (ps2_0_command),       // avalon_ps2_command_sink.data
		.command_valid (ps2_0_command_valid), //                        .valid
		.command_ready (ps2_0_command_ready), //                        .ready
		.data_ready    (ps2_0_data_ready),    //  avalon_ps2_data_source.ready
		.data          (ps2_0_data),          //                        .data
		.data_valid    (ps2_0_data_valid),    //                        .valid
		.PS2_CLK       (ps2_0_PS2_CLK),       //      external_interface.export
		.PS2_DAT       (ps2_0_PS2_DAT)        //                        .export
	);

endmodule
